# Generated by Django 5.2.5 on 2025-09-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('to_road_distance', models.CharField(max_length=20)),
                ('rate', models.CharField(max_length=20)),
                ('scatter_loss_graph_url', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tx_lon', models.FloatField()),
                ('tx_lat', models.FloatField()),
                ('rx_lon', models.FloatField()),
                ('rx_lat', models.FloatField()),
                ('tx_gain', models.IntegerField()),
                ('rx_gain', models.IntegerField()),
                ('freq', models.IntegerField()),
                ('distance_km', models.FloatField()),
                ('median_loss', models.FloatField()),
                ('tx_theta', models.FloatField()),
                ('rx_theta', models.FloatField()),
                ('theta_scatter', models.FloatField()),
                ('area', models.CharField(max_length=100)),
                ('max_height', models.FloatField()),
                ('tx_barrier_distance', models.FloatField()),
                ('tx_barrier_height', models.FloatField()),
                ('rx_barrier_distance', models.FloatField()),
                ('rx_barrier_height', models.FloatField()),
                ('scatterer_lon', models.FloatField()),
                ('scatterer_lat', models.FloatField()),
                ('scatterer_height', models.FloatField()),
                ('image_path', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
