# Generated by Django 5.2.5 on 2025-09-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_areacoverage_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlelink',
            name='rx_height',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlelink',
            name='tx_height',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
