# Generated by Django 5.2.5 on 2025-09-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_singlelink_rx_height_singlelink_tx_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlelink',
            name='diversity_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlelink',
            name='recv_power',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlelink',
            name='reliability',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlelink',
            name='residual_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlelink',
            name='rx_azimuth',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlelink',
            name='trans_power',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlelink',
            name='tx_azimuth',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
