# Generated by Django 5.2.5 on 2025-09-19 03:29

# import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_singlelink_diversity_order_singlelink_recv_power_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dandong',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=80)),
                ('oneway', models.CharField(max_length=80)),
                ('bridge', models.CharField(max_length=80)),
                ('tunnel', models.CharField(max_length=80)),
                # ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'db_table': 'dandong',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='singlelink',
            name='comm_rate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
