# Generated by Django 5.2.5 on 2025-09-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_dandong_singlelink_comm_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areacoverage',
            old_name='rate',
            new_name='coverage_type',
        ),
        migrations.RenameField(
            model_name='areacoverage',
            old_name='scatter_loss_graph_url',
            new_name='image_path',
        ),
        migrations.RenameField(
            model_name='areacoverage',
            old_name='latitude',
            new_name='tx_latitude',
        ),
        migrations.RenameField(
            model_name='areacoverage',
            old_name='longitude',
            new_name='tx_longitude',
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='circle_center_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='circle_center_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='circle_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='eps_cells',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='frequency',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='loss_threshold',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='min_samples',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='p',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='rectangle_max_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='rectangle_max_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='rectangle_min_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='rectangle_min_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='rx_center_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='rx_center_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='tif_path',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='to_road_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='to_road_slope',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='areacoverage',
            name='to_road_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
