# Generated by Django 5.2.5 on 2025-09-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_rate_areacoverage_coverage_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoverage',
            name='diversity_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='rx_gain',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='trans_power',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='tx_gain',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
