# Generated by Django 5.2.5 on 2025-09-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_areacoverage_diversity_order_areacoverage_rx_gain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoverage',
            name='excel_path',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
