# Generated by Django 5.2.5 on 2025-09-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_areacoverage_excel_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacoverage',
            name='excel_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
