# Generated by Django 5.2.5 on 2025-09-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_areacoverage_excel_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlelink',
            name='rx_terrain_height',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlelink',
            name='tx_terrain_height',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
