# Generated by Django 5.2.5 on 2025-10-09 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_singlelink_rx_terrain_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacoverage',
            name='number',
        ),
        migrations.RemoveField(
            model_name='areacoverage',
            name='rx_center_latitude',
        ),
        migrations.RemoveField(
            model_name='areacoverage',
            name='rx_center_longitude',
        ),
        migrations.RemoveField(
            model_name='areacoverage',
            name='to_road_distance',
        ),
        migrations.RemoveField(
            model_name='areacoverage',
            name='to_road_name',
        ),
        migrations.RemoveField(
            model_name='areacoverage',
            name='to_road_slope',
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('center_longitude', models.FloatField()),
                ('center_latitude', models.FloatField()),
                ('count', models.IntegerField()),
                ('to_road_name', models.CharField(max_length=100)),
                ('to_road_slope', models.FloatField()),
                ('to_road_distance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.areacoverage')),
            ],
        ),
    ]
