# Generated by Django 5.2.5 on 2025-10-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_areacoverage_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stations',
            name='number',
        ),
        migrations.AddField(
            model_name='stations',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
