# Generated by Django 5.2.5 on 2025-10-10 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_stations_number_stations_serial_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stations',
            old_name='serial_number',
            new_name='number',
        ),
    ]
