# Generated by Django 5.2.5 on 2025-10-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_rename_serial_number_stations_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoverage',
            name='image_colors',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='image_max',
            field=models.FloatField(default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='image_min',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
