# Generated by Django 5.2.5 on 2025-10-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_areacoverage_image_colors_areacoverage_image_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoverage',
            name='calculation_area',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='calculation_duration',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
