# Generated by Django 5.2.5 on 2025-10-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_areacoverage_calculation_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoverage',
            name='tx_station_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlelink',
            name='rx_station_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlelink',
            name='tx_station_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
