# Generated by Django 5.2.5 on 2025-10-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_areacoverage_tx_station_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlelink',
            name='calculation_duration',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
