# Generated by Django 5.2.5 on 2025-10-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_singlelink_calculation_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoverage',
            name='comm_rate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
