# Generated by Django 5.2.5 on 2025-10-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_areacoverage_comm_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlelink',
            name='final_loss',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
