# Generated by Django 5.2.5 on 2025-10-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_singlelink_final_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoverage',
            name='subrange_circle_center_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='subrange_circle_center_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='subrange_circle_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='subrange_rectangle_max_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='subrange_rectangle_max_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='subrange_rectangle_min_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='subrange_rectangle_min_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='subrange_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
