# Generated by Django 5.2.5 on 2025-10-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_areacoverage_subrange_circle_center_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoverage',
            name='cluster_duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
