# Generated by Django 5.2.5 on 2025-11-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_areacoverage_cluster_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dandong',
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='singlelink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
