# Generated by Django 5.2.5 on 2025-11-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_delete_dandong_areacoverage_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoverage',
            name='prohibited_area_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='prohibited_center_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='prohibited_center_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='prohibited_max_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='prohibited_max_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='prohibited_min_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='prohibited_min_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='prohibited_radius',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
