# Generated by Django 5.2.5 on 2025-11-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_areacoverage_prohibited_area_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoverage',
            name='relay_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='relay_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='relay_to_road_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='relay_to_road_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='areacoverage',
            name='relay_to_road_slope',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
