# Generated by Django 5.2.5 on 2026-01-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_areacoverage_relay_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoverage',
            name='limit_road_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
