# Generated by Django 5.2.5 on 2026-08-14 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stations",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stations",
                to="projects.areacoverage",
            ),
        ),
    ]
