# Generated by Django 5.2.5 on 2026-08-15 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_stations_area_related_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapTileService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='接口名称')),
                ('service_type', models.CharField(choices=[('wms', 'WMS'), ('wmts', 'WMTS'), ('xyz', 'XYZ')], default='wms', max_length=10, verbose_name='服务类型')),
                ('url', models.CharField(help_text='本地示例: http://127.0.0.1:8080/geoserver/zk/wms 或 /geoserver/zk/wms；XYZ 需含 {z}/{x}/{y}', max_length=500, verbose_name='服务地址')),
                ('layers', models.CharField(blank=True, default='', help_text='WMS/WMTS 图层，如 zk:china_roadnet2', max_length=200, verbose_name='图层名')),
                ('format', models.CharField(default='image/png', max_length=50, verbose_name='图片格式')),
                ('tile_matrix_set_id', models.CharField(blank=True, default='EPSG:4326', max_length=50, verbose_name='WMTS矩阵集')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='接口描述')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('show_default', models.BooleanField(default=False, verbose_name='默认显示')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_tile_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '地图接口服务',
                'verbose_name_plural': '地图接口服务',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
