"""
Django settings for scattering project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def _resolve_proj_lib():
    candidates = [
        BASE_DIR / "venv" / "Lib" / "site-packages" / "rasterio" / "proj_data",
        BASE_DIR / ".venv" / "lib" / f"python{os.sys.version_info.major}.{os.sys.version_info.minor}" / "site-packages" / "rasterio" / "proj_data",
    ]
    for cand in candidates:
        if cand.exists():
            return str(cand)
    try:
        import rasterio
        cand = Path(rasterio.__file__).resolve().parent / "proj_data"
        if cand.exists():
            return str(cand)
    except Exception:
        pass
    return ""

_proj_lib = _resolve_proj_lib()
if _proj_lib:
    os.environ["PROJ_LIB"] = _proj_lib


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-35ak1if+ukv95-2=nf*ds2)4cwu-5wl+u=*1h0%=^615#baqdv'
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-35ak1if+ukv95-2=nf*ds2)4cwu-5wl+u=*1h0%=^615#baqdv')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = os.getenv("DEBUG", "False") == "True"

# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.100.89']
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'django_filters',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    # 'drf_spectacular_sidecar',
    'channels',
    'django_celery_results',
    # 'django_celery_beat',

    'users',
    'projects',
    'wslink',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 要放在最前面
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'scattering.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scattering.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        # "ENGINE": "django.contrib.gis.db.backends.postgis",
        'NAME': os.getenv('DB_NAME', 'sstx_data'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', '123456'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', 5432),  # 端口
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'

# 配置媒体文件目录
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Nginx媒体文件访问完整URL
NGINX_MEDIA_URL = os.getenv('NGINX_MEDIA_URL', 'http://localhost:8089/media/')

# DEM高程图文件路径
DEM_PATH = os.getenv('DEM_PATH', '../scripts/ChinaDEM/China_DEM30.tif')


# 设置jwt登录验证
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # 每页数量，可调整
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
}


# token设置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),   # access token 有效期 30 分钟
    # 'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1),
    # 'ACCESS_TOKEN_LIFETIME': timedelta(days=7),      # refresh token 有效期 7 天
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3),
    'ROTATE_REFRESH_TOKENS': True,                    # 每次刷新都生成新 refresh token（推荐）
    'BLACKLIST_AFTER_ROTATION': True,                 # 旧的 refresh token 作废（需要开启黑名单机制）
    'AUTH_HEADER_TYPES': ('Bearer',),                 # 支持 Authorization: Bearer <token>
}


# 允许跨域
CORS_ALLOW_ALL_ORIGINS = True


# SPECTACULAR_SETTINGS = {
#     'SWAGGER_UI_DIST': 'SIDECAR',  # 用sidecar代替
#     'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
#     'REDOC_DIST': 'SIDECAR',
#     'TITLE': 'sstx API接口文档',
#     'DESCRIPTION': 'sstx 项目详情介绍',
#     'VERSION': '1.0.0',
# }


ASGI_APPLICATION = 'scattering.asgi.application'


# 统一生成 Redis URL，自动处理有无密码的情况
def get_redis_url(db_index):
    if REDIS_PASSWORD:
        return f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{db_index}"
    return f"redis://{REDIS_HOST}:{REDIS_PORT}/{db_index}"


# Redis 基础连接信息
REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
REDIS_PORT = os.getenv('REDIS_PORT', '6379')
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', None)  # 如果无密码，环境变量不传即可

# Redis 数据库索引规划
REDIS_DB_INDEX_CHANNELS = os.getenv('REDIS_DB_INDEX_CHANNELS', 0)   # WebSocket 消息通道
REDIS_DB_INDEX_CACHE    = os.getenv('REDIS_DB_INDEX_CACHE', 1)   # Django 默认缓存 (Session/Admin等)
REDIS_DB_INDEX_BROKER   = os.getenv('REDIS_DB_INDEX_BROKER', 2)   # Celery 任务队列 (Broker)
REDIS_DB_INDEX_RESULT   = os.getenv('REDIS_DB_INDEX_RESULT', 3)   # Celery 任务结果 (Result Backend)
REDIS_DB_INDEX_BUSINESS = os.getenv('REDIS_DB_INDEX_BUSINESS', 4)   # 业务数据

# Channel Layers 配置 (WebSocket)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            # 这里直接调用函数，确保密码逻辑统一
            'hosts': [get_redis_url(REDIS_DB_INDEX_CHANNELS)],  # DB 0
        },
    },
}

# Celery 配置
# 优先读取专用环境变量，如果没有，则使用上面生成的标准 URL
CELERY_BROKER_URL = get_redis_url(REDIS_DB_INDEX_BROKER)  # DB 2
CELERY_RESULT_BACKEND = get_redis_url(REDIS_DB_INDEX_RESULT)  # DB 3
CELERY_CACHE_BACKEND = 'django-cache'  # 使用下方的 CACHES['default']
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_ENABLE_UTC = True

# Django Caches & 业务 Redis 配置
CACHES = {
    # 默认缓存: Django 系统自身使用 (Session, 页面缓存等)
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": get_redis_url(REDIS_DB_INDEX_CACHE),  # DB 1
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "business": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": get_redis_url(REDIS_DB_INDEX_BUSINESS),  # DB 4
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # 连接池配置：防止高并发下连接数耗尽
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
            # 自动转码：取出来的数据直接是 str，不是 bytes
            "DECODE_RESPONSES": True,
        }
    }
}
