// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Backlight: typeof import('./src/components/backlight/index.vue')['default']
    BaseBox: typeof import('./src/components/baseBox/index.vue')['default']
    ColumnChart: typeof import('./src/components/footer/columnChart.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    OperatingButton: typeof import('./src/components/operatingButton/index.vue')['default']
    PanelContainer: typeof import('./src/components/panelContainer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WordCloud: typeof import('./src/components/wordCloud/index.vue')['default']
  }
}
